version: '3.8'
services:
  # make sure implements retry connectDB 5 times each 5s
  dbhost:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: rifandani
      POSTGRES_USER: rizeki
      POSTGRES_DB: mydb
    volumes:
      # - ./pgdata:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redisCache:
      image: redis:6.2-alpine
      container_name: xchangerfx_redis
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - 6379:6379
      volumes:
        - ./redis:/db
  expressapp:
    # use my own custom image
    image: nextwebb/express:latest
    # make sure it starts postgres first
    depends_on:
      - dbhost
      - redisCache
    ports:
      - '8000:8000'

volumes:
  pgdata:
